grails-app/domain/tp/mbds/com/SaleAd.groovy
package tp.mbds.com

class SaleAd {

    String title, description, longDescription
    Date dateCreated, lastUpdated
    List illustrations
    Float price

    static hasMany = [illustrations: Illustration]

    static belongsTo = [author: User]

    static constraints = {
        title blank : false, nullable : false
        description blank : false, nullable : false
        longDescription blank : false, nullable : false
        illustrations nullable: true
        price min : 0F
    }

    static mapping = {
        longDescription type : 'text'
        messages lazy: false
    }
}

grails-app/domain/tp/mbds/com/User.groovy
package tp.mbds.com

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString
import grails.compiler.GrailsCompileStatic

@GrailsCompileStatic
@EqualsAndHashCode(includes='username')
@ToString(includes='username', includeNames=true, includePackage=false)
class User implements Serializable {

    private static final long serialVersionUID = 1

    String username
    String password
    boolean enabled = true
    boolean accountExpired
    boolean accountLocked
    boolean passwordExpired

    static hasMany = [saleAds : SaleAd]

    Set<Role> getAuthorities() {
        (UserRole.findAllByUser(this) as List<UserRole>)*.role as Set<Role>
    }

    static constraints = {
        password nullable: true, blank: false, password: true
        username nullable: false, blank: false, unique: true
        saleAds nullable: true
    }

    static mapping = {
	    password column: '`password`'
    }
}

grails-app/controllers/tp/mbds/com/UserController.groovy
package tp.mbds.com

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class UserController {

    UserService userService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond userService.list(params), model:[userCount: userService.count()]
    }

    def show(Long id) {
        respond userService.get(id)
    }

    def create() {
        respond new User(params)
    }

    def save(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            userService.save(user)
            UserRole.create(user,Role.get(params.role), true)
        } catch (ValidationException e) {
            respond user.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*' { respond user, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond userService.get(id)
    }

    def update() {
        def user = User.get(params.id)
        if (user == null) {
            notFound()
            return
        }

        try {
            UserRole.removeAll(user)
            UserRole.create(user,Role.get(params.role), true)
            if (params.password != ''){
                user.password = params.password
            }
            if (params.username != user.username){
                user.username = params.username
            }
            userService.save(user)
        } catch (ValidationException e) {
            respond user.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*'{ respond user, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }
        UserRole.removeAll(User.get(id))
        userService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'user.label', default: 'User'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/user/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<a href="#create-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                             default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
    </ul>
</div>

<section class="row colset-2-its">
    <div id="create-user" class="content scaffold-create" role="main">
        <h1><g:message code="default.create.label" args="[entityName]"/></h1>
        <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
        </g:if>
        <g:hasErrors bean="${this.user}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.user}" var="error">
                    <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                            error="${error}"/></li>
                </g:eachError>
            </ul>
        </g:hasErrors>
        <g:form resource="${this.user}" method="POST">
        %{--        <fieldset class="form">--}%
        %{--            <f:all bean="user"/>--}%
        %{--        </fieldset>--}%
            <fieldset class="form">
                <div class="form-group required">
                    <label for="username">Username
                        <span class="required-indicator">*</span>
                    </label><input class="form-control" type="text" name="username" value="" required=""
                                   id="username">
                </div>

                <div class="form-group required">
                    <label for="password">Password
                        <span class="required-indicator">*</span>
                    </label><input class="form-control" type="password" name="password" required="" value=""
                                   id="password">
                </div>

                %{--            <div class="form-group">--}%
                %{--                <label for="passwordExpired">Password Expired</label><input type="hidden" name="_passwordExpired"><input--}%
                %{--                    type="checkbox" name="passwordExpired" id="passwordExpired">--}%
                %{--            </div>--}%

                %{--            <div class="form-group">--}%
                %{--                <label for="accountLocked">Account Locked</label><input type="hidden" name="_accountLocked"><input--}%
                %{--                    type="checkbox" name="accountLocked" id="accountLocked">--}%
                %{--            </div>--}%

                %{--            <div class="form-group">--}%
                %{--                <label for="accountExpired">Account Expired</label><input type="hidden" name="_accountExpired"><input--}%
                %{--                    type="checkbox" name="accountExpired" id="accountExpired">--}%
                %{--            </div>--}%

                %{--            <div class="form-group">--}%
                %{--                <label for="enabled">Enabled</label><input type="hidden" name="_enabled"><input type="checkbox"--}%
                %{--                                                                                                name="enabled"--}%
                %{--                                                                                                checked="checked"--}%
                %{--                                                                                                id="enabled">--}%
                %{--            </div>--}%

                %{--                <fieldset class="buttons">--}%
                <div class="form-group required">
                    <label for="role">Rôle
                        <span class="required-indicator">*</span>
                    </label>
                    <g:select class="form-control" from="${tp.mbds.com.Role.list()}"
                              name="role" optionKey="id" optionValue="authority"/>
                </div>

                <g:submitButton class="btn btn-primary" name="create"
                                value="${message(code: 'default.button.create.label', default: 'Create')}"/>
            </fieldset>
        </g:form>
    </div>
</section>

</body>
</html>

grails-app/views/user/edit.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<a href="#edit-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                           default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>
<section class="row colset-2-its"><fieldset class="form">
    <div id="edit-user" class="content scaffold-edit" role="main">
        <h1><g:message code="default.edit.label" args="[entityName]"/></h1>
        <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
        </g:if>
        <g:hasErrors bean="${this.user}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.user}" var="error">
                    <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                            error="${error}"/></li>
                </g:eachError>
            </ul>
        </g:hasErrors>
        <g:form resource="${this.user}" method="PUT">

            <g:hiddenField name="version" value="${this.user?.version}"/>

            <div class="form-group">
                <label for="password">Password</label><input class="form-control" type="password" name="password"
                                                             value="" id="password">
            </div>

            <div class="form-group required">
                <label for="username">Username
                    <span class="required-indicator">*</span>
                </label><input class="form-control" type="text" name="username" value="${this.user.username}"
                               required="" id="username">
            </div>

            <div class="form-group">
                <label style="display: none;" for="passwordExpired">Password Expired</label><input type="hidden"
                                                                                                   name="_passwordExpired"><input
                    type="hidden"
                    class="form-control" type="checkbox" name="passwordExpired" id="passwordExpired">
            </div>

            <div class="form-group">
                <label style="display: none;" for="accountLocked">Account Locked</label><input type="hidden"
                                                                                               name="_accountLocked"><input
                    type="hidden"
                    class="form-control" type="checkbox" name="accountLocked" id="accountLocked">
            </div>

            <div class="form-group">
                <label style="display: none;" for="accountExpired">Account Expired</label><input type="hidden"
                                                                                                 name="_accountExpired"><input
                    type="hidden"
                    class="form-control" type="checkbox" name="accountExpired" id="accountExpired">
            </div>

            <div class="form-group">
                <label style="display: none;" for="enabled">Enabled</label><input type="hidden" name="_enabled"><input
                    type="hidden"
                    class="form-control"
                    type="checkbox"
                    name="enabled"
                    checked="checked"
                    id="enabled">
            </div>

            <div class="form-group">
                <label for="role">Rôle</label>
                <g:select class="form-control"
                          from="${tp.mbds.com.Role.list()}" name="role"
                          optionKey="id"
                          optionValue="authority" value="${this.user.getAuthorities()[0].id}"/>
            </div>
            <g:submitButton name="update" class="btn btn-primary" type="submit"
                            value="${message(code: 'default.button.update.label', default: 'Update')}"/>

        </g:form>
    </div>
</section>
</body>
</html>

grails-app/views/user/index.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<a href="#list-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                           default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="content" role="main">
    <section class="row colset-2-its">
        <div id="list-user" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]"/></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
        %{--    <f:table collection="${userList}"/>--}%
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Username</th>
                    <th>Rôle</th>
                    <th>SaleAds</th>
                </tr>
                </thead>
                <tbody>
                <g:each in="${userList}" var="user">
                    <tr>
                        <td>${user.id}</td>
                        <td>
                            <g:link controller="user" action="show" id="${user.id}">
                                ${user.username}
                            </g:link>
                        </td>
                        <g:each in="${user.getAuthorities()}" var="authority">
                            <td><strong>${authority.authority}</strong></td>
                        </g:each>
                        <td>
                            <g:each in="${user.saleAds}" var="saleAd">
                                <table>
                                    <tr>
                                        <td>
                                            <g:link controller="saleAd" action="show" id="${saleAd.id}">
                                                ${saleAd.title}
                                            </g:link>
                                        </td>
                                    </tr>
                                </table>
                            </g:each>
                        </td>
                    </tr>
                </g:each>
                </tbody>
            </thead>
            </table>
        </div>

        <div class="pagination">
            <g:paginate total="${saleAdCount ?: 0}"/>
        </div>
    </section>
</div>
</body>
</html>

grails-app/views/user/show.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<a href="#show-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                           default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>
<section class="row colset-2-its"><fieldset class="form">
    <div id="show-user" class="content scaffold-show" role="main">
        <h1><g:message code="default.show.label" args="[entityName]"/></h1>
        <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
        </g:if>
        <ol class="property-list user">

            <li class="fieldcontain">
                <span id="password-label" class="property-label">Password</span>

                <div class="property-value" aria-labelledby="password-label">${user.password}</div>
            </li>

            <li class="fieldcontain">
                <span id="username-label" class="property-label">Username</span>

                <div class="property-value" aria-labelledby="username-label">${user.username}</div>
            </li>

            <li class="fieldcontain">
                <span id="saleAds-label" class="property-label">Sale Ads</span>

                <div class="property-value" aria-labelledby="saleAds-label">
                    <ul>
                        <g:each in="${user.saleAds}" var="saleAd">
                            <li>
                                <g:link controller="saleAd" action="show" id="${saleAd.id}">
                                    ${saleAd.title}
                                </g:link>
                            </li>
                        </g:each>
                    </ul>
                </div>
            </li>

            <li class="fieldcontain">
                <span id="passwordExpired-label" class="property-label">Password Expired</span>

                <div class="property-value" aria-labelledby="passwordExpired-label">${user.passwordExpired}</div>
            </li>

            <li class="fieldcontain">
                <span id="accountLocked-label" class="property-label">Account Locked</span>

                <div class="property-value" aria-labelledby="accountLocked-label">${user.accountLocked}</div>
            </li>

            <li class="fieldcontain">
                <span id="accountExpired-label" class="property-label">Account Expired</span>

                <div class="property-value" aria-labelledby="accountExpired-label">${user.accountExpired}</div>
            </li>

            <li class="fieldcontain">
                <span id="enabled-label" class="property-label">Enabled</span>

                <div class="property-value" aria-labelledby="enabled-label">${user.enabled}</div>
            </li>
            <li class="fieldcontain">
                <span id="role-label" class="property-label">Role</span>

                <div class="property-value" aria-labelledby="role-label">${user.getAuthorities()[0].authority}</div>
            </li>
        </ol>
        <g:form resource="${this.user}" method="DELETE">
            <fieldset class="buttons">
                <g:link class="edit" action="edit" resource="${this.user}"><g:message code="default.button.edit.label"
                                                                                      default="Edit"/></g:link>
                <input class="delete" type="submit"
                       value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                       onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
            </fieldset>
        </g:form>
    </div>
</fieldset>
</body>
</html>